 //WAP (Write a Programme) to Display Your Name
 #include<stdio.h>	//Header File
 #include<conio.h>      //Header File
 main()                 //Starter Function
 {                      //Open Curley Brackets
 clrscr();              //For Clear Screen
 printf("Welcome");     //Statement Block
 }                      //Close Curley Brackets




 // Ctrl + F9 = Compile & Find Error & Convert to Machine Level
 // Alt + F5 = Run/Output/Execute


 //Programme Make : High Level             Stdio.h     	     Conio.h
 //Feature : Low Level                    std=Standard     Con = Console
 //Result : Machine Level                 i=input	   i = input
 //					  o=output         o = output
 //					 .h header file   .h = header file