 //WAP (Write a Programme) to Display Your Name
 #include<iostream.h>	//Header File
 #include<conio.h>      //Header File
 main()                 //Starter Function
 {                      //Open Curley Brackets
 clrscr();              //For Clear Screen
 cout<<"Welcome";     //Statement Block
 }                      //Close Curley Brackets


 // << : L Shift

 // Ctrl + F9 = Compile & Find Error & Convert to Machine Level
 // Alt + F5 = Run/Output/Execute


 //Programme Make : High Level             Iostream.h  	     Conio.h
 //Feature : Low Level                    Stream = File    Con = Console
 //Result : Machine Level                 i=input	   i = input
 //					  o=output         o = output
 //					 .h header file   .h = header file